# Generated by Django 4.2.7 on 2023-11-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='М', max_length=10),
        ),
    ]
