# Generated by Django 4.2.7 on 2023-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_level', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(upload_to='persons_images'),
        ),
    ]
